# Generated by Django 5.0.6 on 2024-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('production_piece_count', models.IntegerField()),
                ('defective_piece_count', models.IntegerField()),
                ('machine', models.CharField(max_length=500)),
                ('report_text', models.TextField()),
            ],
        ),
    ]
